"""empty message

Revision ID: 0a60c8ee5682
Revises: 8519a08311f4
Create Date: 2024-08-14 11:02:58.154068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a60c8ee5682'
down_revision = '8519a08311f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=250), nullable=False))
        batch_op.drop_column('last_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=250), nullable=True))
        batch_op.drop_column('last_name')
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('lastname')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
