"""empty message

Revision ID: 30ed6049d656
Revises: 747eaacc3f16
Create Date: 2024-08-27 11:49:00.614678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ed6049d656'
down_revision = '747eaacc3f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_companions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('companion_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.alter_column('ad_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.alter_column('ad_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favorite_companions', schema=None) as batch_op:
        batch_op.alter_column('companion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
