"""empty message

Revision ID: 36cb3bea2410
Revises: 30ed6049d656
Create Date: 2024-08-27 11:50:18.869903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cb3bea2410'
down_revision = '30ed6049d656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_ads', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ad_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favorite_companions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('companion_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.alter_column('ad_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.alter_column('ad_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('favorite_companions', schema=None) as batch_op:
        batch_op.alter_column('companion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('favorite_ads', schema=None) as batch_op:
        batch_op.alter_column('ad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
