"""empty message

Revision ID: 516858434dff
Revises: 9384a269046f
Create Date: 2024-08-19 17:33:15.580128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516858434dff'
down_revision = '9384a269046f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companions', schema=None) as batch_op:
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
