"""empty message

Revision ID: 747eaacc3f16
Revises: 8f013b789d9c
Create Date: 2024-08-27 11:47:28.364890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747eaacc3f16'
down_revision = '8f013b789d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_ads', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ad_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_ads', schema=None) as batch_op:
        batch_op.alter_column('ad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
