"""empty message

Revision ID: 8a3bdc1e1469
Revises: 9e437e515bed
Create Date: 2024-08-22 10:29:21.654152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3bdc1e1469'
down_revision = '9e437e515bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companions', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
