"""empty message

<<<<<<<< HEAD:migrations/versions/04b99c8ca236_.py
Revision ID: 04b99c8ca236
Revises: 
Create Date: 2024-08-27 10:50:11.183341
========
Revision ID: 8f013b789d9c
Revises: 
Create Date: 2024-08-27 09:14:26.743229
>>>>>>>> c352d76e2aaaa9ad2c7d8e1eecb78a3c16eba178:migrations/versions/8f013b789d9c_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/04b99c8ca236_.py
revision = '04b99c8ca236'
========
revision = '8f013b789d9c'
>>>>>>>> c352d76e2aaaa9ad2c7d8e1eecb78a3c16eba178:migrations/versions/8f013b789d9c_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('lastname', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=250), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('role', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('companions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('province', sa.String(length=250), nullable=True),
    sa.Column('birthdate', sa.String(length=250), nullable=True),
    sa.Column('availability_hours', sa.Boolean(), nullable=True),
    sa.Column('availability_days', sa.Boolean(), nullable=True),
    sa.Column('availability_weeks', sa.Boolean(), nullable=True),
    sa.Column('availability_live_in', sa.Boolean(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('service_cost', sa.Integer(), nullable=True),
    sa.Column('facebook', sa.String(length=250), nullable=True),
    sa.Column('instagram', sa.String(length=250), nullable=True),
    sa.Column('twitter', sa.String(length=250), nullable=True),
    sa.Column('linkedin', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('lastname', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=250), nullable=False),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('birthdate', sa.String(length=250), nullable=False),
    sa.Column('dependency', sa.String(length=250), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('province', sa.String(length=250), nullable=True),
    sa.Column('availability', sa.String(length=250), nullable=True),
    sa.Column('tags', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('type', sa.Enum('OUT', 'IN', name='type'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('max_cost', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REJECTED', 'OK', 'FINISH', name='status'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hired', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hired'], ['companions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_companions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('companion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('companion_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('companion_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('statusContract', sa.Enum('PENDING', 'REJECTED', 'OK', name='statuscontract'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscriptions')
    op.drop_table('favorite_ads')
    op.drop_table('ratings')
    op.drop_table('favorite_companions')
    op.drop_table('ads')
    op.drop_table('patients')
    op.drop_table('companions')
    op.drop_table('users')
    # ### end Alembic commands ###
