"""empty message

Revision ID: 9e437e515bed
Revises: 3cc08b10fcde
Create Date: 2024-08-22 08:12:41.759338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e437e515bed'
down_revision = '3cc08b10fcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_companions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('companion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favourite_companions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_companions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('companion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], name='favourite_companions_companion_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favourite_companions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favourite_companions_pkey')
    )
    op.drop_table('favorite_companions')
    # ### end Alembic commands ###
