"""empty message

Revision ID: cf821b67ceac
Revises: 1477ea000a26
Create Date: 2024-08-21 14:35:38.200848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf821b67ceac'
down_revision = '1477ea000a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('companion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favourite_companions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_companions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('companion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['companions.id'], name='favourite_companions_companion_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='favourite_companions_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favourite_companions_pkey')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###
