"""empty message

Revision ID: ea189e625fcd
Revises: c232a27a26e0
Create Date: 2024-08-15 16:40:58.605786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea189e625fcd'
down_revision = 'c232a27a26e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(length=50), nullable=False))
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('availability',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('availability',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('alias')

    # ### end Alembic commands ###
