"""empty message

Revision ID: ea75ff8524b4
Revises: 9bcd0752cf24
Create Date: 2024-08-12 16:42:36.879798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea75ff8524b4'
down_revision = '9bcd0752cf24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('birthdate',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthdate',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
